# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20180516_1857'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cart',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='updated',
        ),
        migrations.AlterField(
            model_name='cart',
            name='tools',
            field=models.ManyToManyField(blank=True, null=True, to='tools.Tool'),
        ),
    ]
