# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20180516_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
