# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_auto_20180514_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='brand',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
